[package]
name = "antikythera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.9"
sdl2 = { version = "0.35.2", features = ["gfx"] }
